#For SQLite:
default: &default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  
development:
  <<: *default
  database: QuemVotarApi_development

test:
  <<: *default
  database: QuemVotarApi_test

#For mySQL:
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   socket: /var/lib/mysql/mysql.sock

# development:
#   <<: *default
#   database: QuemVotarApi_development

# test:
#   <<: *default
#   database: QuemVotarApi_test

# production:
#   <<: *default
#   database: QuemVotarApi_production
#   username: QuemVotarApi
#   password: <%= ENV['QUEMVOTARAPI_DATABASE_PASSWORD'] %>
